app: wordlist
stage: dev

component: scf
name: notionAPI

inputs:
  src:
    src: ./src
    exclude:
      - .env
  type: web
  name: notionBot
  description: Save word to Notion. 
  region: ap-beijing
  runtime: Nodejs16.13
  installDependency: true
  timeout: 15
  events: 
    - apigw: 
        parameters: 
          serviceId: service-kjstrjbf
          protocols:
            - https
          environment: release
          endpoints: 
            - path: /
              method: GET
