app: wordlist
stage: prod

component: http
name: wordlistAPI
inputs:
  src:
    src: ./src
    exclude:
      - .env
  faas:
    runtime: Nodejs18.15
    framework: express
    name: ${name}-${stage}-${app}
    environments: #  环境变量
      - key: OAUTH_CLIENT_ID
        value: ${env:OAUTH_CLIENT_ID}
      - key: OAUTH_CLIENT_SECRET
        value: ${env:OAUTH_CLIENT_SECRET}
      - key: YOUDAO_ID
        value: ${env:YOUDAO_ID}
      - key: YOUDAO_TOKEN
        value: ${env:YOUDAO_TOKEN}
      - key: azureOpenAIApiKey
        value: ${env:azureOpenAIApiKey}
      - key: azureOpenAIApiInstanceName
        value: ${env:AZUREOPENAIAPIINSTANCENAME}
      - key: azureOpenAIApiDeploymentName
        value: ${env:AZUREOPENAIAPIDEPLOYMENTNAME}
      - key: azureOpenAIApiVersion
        value: ${env:AZUREOPENAIAPIVERSION}
    events:
      - http:
          parameters:
            netConfig:
              enableIntranet: true
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE
