app: wordlistAPI
stage: prod

component: http
name: wordlist

inputs:
  src:
    src: ./src
    exclude:
      - .env
  faas:
    runtime: Nodejs18.15
    framework: express
    name: ${name}
    events:
      - http:
          parameters:
            netConfig:
              enableIntranet: true
              enableExtranet: true
            qualifier: $DEFAULT
            authType: NONE
