app: wordlist
stage: dev

component: scf
name: notionAPI

inputs:
  src:
    src: ./src
    exclude:
      - .env
  type: web
  name: notionBot
  description: Save word to Notion. 
  region: ap-beijing
  runtime: Nodejs18.15
  installDependency: false
  vpcConfig: # 可以不指定
    vpcId: vpc-rgvuuoio
    subnetId: subnet-12q7b7zp
  eip: true
  timeout: 15