CREATE TABLE users (
    USER_ID VARCHAR(40) NOT NULL, 
    NOTION_TOKEN VARCHAR(60) NOT NULL, 
    YOUDAO_ID VARCHAR(30), 
    YOUDAO_TOKEN VARCHAR(40), 
    database_id VARCHAR(50) NOT NULL, 
    TOKEN VARCHAR(60) NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
    PRIMARY KEY (USER_ID)
);