CREATE TABLE users (USER_ID VARCHAR(40) NOT NULL, 
    NOTION_KEY VARCHAR(40) NOT NULL, 
    YOUDAO_ID VARCHAR(40), 
    YOUDAO_KEY VARCHAR(40), 
    database_id VARCHAR(60) NOT NULL, 
    PRIMARY KEY (USER_ID)
);