name: Deploy to tencnet SCF
on: [push]
jobs: 
  Deploy:
    name: Try to deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with: 
        node-version: '16'
    - name: install serverless
      run: npm install -g serverless
    - name: install node_modules
      run: |
        cd src
        npm install
    - name: set config.js
      run: echo "$CONFIG" > ./src/config.js
      env: 
        CONFIG: ${{ secrets.CONFIG }}
    - name: deploy
      shell: bash
      run: sls deploy --debug
      env: 
        SERVERLESS_PLATFORM_VENDOR: tencent
        SLS_GEO_LOCATION: cn
        STAGE: prod
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
      
