name: Deploy to tencnet SCF
on: [push]
jobs: 
  Deploy:
    name: Try to deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with: 
        node-version: '16'
    - name: npm install, build
      shell: bash
      env: 
        TENCENT_SECRET_ID: ${{secrets.TENCENT_SECRET_ID}}
        TENCENT_SECRET_KEY: ${{secrets.TENCENT_SECRET_KEY}}
      run: |
        npm install -g serverless
        echo "SERVERLESS_PLATFORM_VENDOR=tencent" >> .env
        echo "TENCENT_SECRET_ID=$TENCENT_SECRET_ID" >> .env
        echo "TENCENT_SECRET_KEY=$TENCENT_SECRET_KEY" >> .env
        sls deploy > log.txt
        tail -30 log.txt
    - name: Archive log.txt
      uses: actions/upload-artifact@v2
      with:
        name: deploy-log
        path: log.txt
